name: google_tasks
description: Google Tasks clone
version: 1.0.0+1
environment:
  sdk: ">=2.4.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cloud_firestore: any
  cupertino_icons: any
  disposable_provider: any
  firebase_analytics: any
  firebase_auth: any
  firebase_core: any
  firebase_crashlytics: any
  firestore_ref:
  mono_kit:
    git:
      url: https://github.com/mono0926/flutter_mono_kit.git
      ref: develop
  firebase_performance: any
  provider: any
  route_observer_mixin: any
  rxdart: any
  simple_logger: any
  undraw: any
  google_sign_in: any
  cloud_functions: any
  cached_network_image:
    git:
      url: https://github.com/renefloor/flutter_cached_network_image.git
      ref: v2.0.0-rc
dev_dependencies:
  flutter_test:
    sdk: flutter
  intl_translation: any
  pedantic_mono: any
flutter:
  uses-material-design: true