name: google_tasks
description: Google Tasks clone
version: 1.0.0+1
environment:
  sdk: ">=2.7.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cloud_firestore: any
  cupertino_icons: any
  disposable_provider: any
  firebase_analytics: any
  firebase_auth: any
  firebase_core: any
  firebase_crashlytics: any
  firestore_ref: any
  json_annotation: any
  mono_kit: ^0.14.0-dev
  firebase_performance: any
  provider: any
  route_observer_mixin: any
  rxdart: any
  simple_logger: any
  undraw: any
  google_sign_in: any
  cloud_functions: any
  cached_network_image: any
  flutter_svg: ^0.17.3+1
dev_dependencies:
  flutter_test:
    sdk: flutter
  intl_translation: any
  build_runner: any
  json_serializable: any
  pedantic_mono: any
flutter:
  uses-material-design: true